### ISSUE TITLE
세가지 선택지를 어떻게 받아올까요?

### ISSUE THREAD

**Issue by Lukaid** [bestmealever/Thebestmeal_Spring#2]
flask로 서버를 만들었을때 문제점이, 선택지를 서버의 메모리에 올려서 동시에 두명 이상의 사용자가 선택지를 고를 경우, 간섭현상이 발생 했음.

이를 전체 JS코딩으로 바꿔, 클라이언트의 메모리에 각 선택지를 저장하는 방식으로 변경

세가지 선택을 마쳤을 경우에만 AJAX통신을 통해 서버로 선택지를 전달하여 API실행

**Comment by projectjjj** [comment]
1번 선택 -> 2번 선택 -> 추천 (저장값 2개)
1번 선택 안함 -> 2번 선택 -> 3번 선택 -> 추천 (저장값 3개)
- 선택지에따라 저장값 개수가 달라져서 임의로 3개 모두 값이 저장되게끔 수정. (추후 원래대로 수정가능)
- 선택을 안했을 때 undefined 되는 값은 어떻게 처리되는지 고민.

**Comment by Lukaid** [comment]
민님이 만든 js에 SprignAPI연결하여 해결
