### ISSUE TITLE
MySQL에서 값을 Array 로 넣을 수 있을까요? 효율적인 데이터 처리 

### ISSUE THREAD

**Issue by jieun-dev1** [bestmealever/Thebestmeal_Spring#5]

**Comment by dlfnek** [comment]
MySQL 등 관계형 데이터베이스에서는 컬럼 값에 Array가 들어갈 수 없음.
대신, 테이블끼리 관계를 맺어줌으로써 서로의 정보를 읽어올 수 있기 때문에 이를 활용하여 DB를 잘 설계하기!!
